package com.bank.signature.domain.model.entity;

import lombok.Builder;
import lombok.Value;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain entity representing an idempotency record.
 * 
 * <p>Stores information about a processed request to prevent duplicate processing.
 * Used to implement idempotent API operations.</p>
 * 
 * <p><b>Hexagonal Architecture:</b> Pure domain entity with no framework dependencies.</p>
 * 
 * @since Story 10.5
 */
@Value
@Builder
public class IdempotencyRecord {
    
    /**
     * Unique identifier for the idempotency record.
     * Typically a UUID generated by the client or auto-generated by the system.
     */
    UUID id;
    
    /**
     * Idempotency key from the Idempotency-Key header.
     * Used to identify duplicate requests.
     */
    String idempotencyKey;
    
    /**
     * SHA-256 hash of the request body.
     * Used to detect if the same key is reused with a different request body (conflict).
     */
    String requestHash;
    
    /**
     * HTTP status code of the original response.
     * Used to replay the same status code on duplicate requests.
     */
    Integer statusCode;
    
    /**
     * Original response body (JSON serialized).
     * Used to replay the same response on duplicate requests.
     */
    String responseBody;
    
    /**
     * Timestamp when the record was created.
     */
    Instant createdAt;
    
    /**
     * Timestamp when the record expires (TTL: 24 hours).
     * After this time, the record can be deleted and the key can be reused.
     */
    Instant expiresAt;
    
    /**
     * Checks if the record has expired.
     * 
     * @param now Current timestamp
     * @return true if expiresAt is before now, false otherwise
     */
    public boolean isExpired(Instant now) {
        return expiresAt.isBefore(now);
    }
    
    /**
     * Checks if the request hash matches.
     * 
     * @param hash Request hash to compare
     * @return true if requestHash equals hash, false otherwise
     */
    public boolean matchesRequestHash(String hash) {
        return requestHash.equals(hash);
    }
}

