package com.singularbank.signature.routing.infrastructure.observability.slo;

import com.singularbank.signature.routing.application.dto.SLOReportDTO;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * SLO Report Service
 * 
 * Generates human-readable SLO reports in various formats:
 * - Markdown (for emails, documentation)
 * - PDF (future enhancement - requires iText library)
 * 
 * @author BMAD DevOps
 * @since Story 9.6
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SLOReportService {
    
    /**
     * Generate Markdown report from SLO data.
     * Suitable for email bodies or documentation.
     * 
     * @param report SLO report data
     * @return Markdown-formatted report
     */
    public String generateMarkdown(SLOReportDTO report) {
        StringBuilder md = new StringBuilder();
        
        md.append("# 📊 SLO Compliance Report\n\n");
        md.append(String.format("**Period:** %s  \n", report.getPeriod()));
        md.append(String.format("**Generated:** %s  \n", report.getGeneratedAt()));
        md.append(String.format("**Status:** %s  \n\n", getStatusEmoji(report.getSloStatus())));
        
        md.append("---\n\n");
        
        // Availability SLO Section
        md.append("## 🎯 Availability SLO (Target: ≥99.9%)\n\n");
        md.append(String.format("- **Current Availability:** %.4f%%\n", report.getAvailability() * 100));
        md.append(String.format("- **Total Requests:** %,d\n", report.getTotalRequests()));
        md.append(String.format("- **Failed Requests:** %,d (5xx errors)\n", report.getFailedRequests()));
        md.append(String.format("- **SLO Target:** %.1f%%\n\n", 99.9));
        
        String availabilityStatus = report.getAvailability() >= 0.999 ? "✅ **PASSING**" : "❌ **FAILING**";
        md.append(String.format("**Result:** %s\n\n", availabilityStatus));
        
        // Error Budget Section
        md.append("---\n\n");
        md.append("## 💰 Error Budget\n\n");
        md.append(String.format("- **Budget Allowed:** %.4f%% (43 min/month downtime)\n", report.getErrorBudgetAllowed() * 100));
        md.append(String.format("- **Budget Consumed:** %.4f%%\n", report.getErrorBudgetConsumed() * 100));
        md.append(String.format("- **Budget Remaining:** %.4f%% (%s)\n",
            report.getErrorBudgetRemaining() * 100,
            report.getErrorBudgetRemaining() >= 0 ? "✅" : "❌ EXHAUSTED"
        ));
        md.append(String.format("- **Budget Remaining (%):** %.2f%% of total budget\n\n",
            report.getErrorBudgetRemainingPercent() * 100
        ));
        
        // Error Budget Health Gauge
        md.append(getErrorBudgetGauge(report.getErrorBudgetRemainingPercent()));
        md.append("\n\n");
        
        // Performance SLO Section
        md.append("---\n\n");
        md.append("## ⚡ Performance SLO (Target: P99 < 300ms)\n\n");
        md.append(String.format("- **P99 Latency:** %.0fms\n", report.getP99Latency() * 1000));
        md.append(String.format("- **Target:** <300ms\n\n"));
        
        String performanceStatus = report.getPerformanceSloMet() ? "✅ **PASSING**" : "❌ **FAILING**";
        md.append(String.format("**Result:** %s\n\n", performanceStatus));
        
        // Recommendations Section
        md.append("---\n\n");
        md.append("## 📋 Recommendations\n\n");
        md.append(report.getRecommendations());
        md.append("\n\n");
        
        // Footer
        md.append("---\n\n");
        md.append("*Generated by Signature Router SLO Monitoring*  \n");
        md.append("*Dashboard: http://localhost:3000/d/slo-compliance*  \n");
        
        return md.toString();
    }
    
    /**
     * Get status emoji based on SLO status.
     */
    private String getStatusEmoji(com.singularbank.signature.routing.domain.model.valueobject.SLOStatus status) {
        switch (status) {
            case COMPLIANT:
                return "✅ COMPLIANT";
            case AT_RISK:
                return "⚠️ AT RISK";
            case VIOLATED:
                return "❌ VIOLATED";
            default:
                return "❓ UNKNOWN";
        }
    }
    
    /**
     * Generate ASCII gauge for error budget remaining.
     */
    private String getErrorBudgetGauge(double remainingPercent) {
        int barLength = 20;
        int filled = (int) (remainingPercent * barLength);
        filled = Math.max(0, Math.min(barLength, filled)); // Clamp to 0-20
        
        StringBuilder gauge = new StringBuilder("```\nError Budget: [");
        
        for (int i = 0; i < barLength; i++) {
            if (i < filled) {
                gauge.append("█");
            } else {
                gauge.append("░");
            }
        }
        
        gauge.append("] ");
        gauge.append(String.format("%.0f%%", remainingPercent * 100));
        gauge.append("\n```");
        
        return gauge.toString();
    }
    
    /**
     * Generate plain text summary for logging/notifications.
     * 
     * @param report SLO report data
     * @return Plain text summary
     */
    public String generatePlainTextSummary(SLOReportDTO report) {
        return String.format(
            "SLO Report %s: Availability=%.2f%%, ErrorBudget=%.0f%% remaining, Status=%s",
            report.getPeriod(),
            report.getAvailability() * 100,
            report.getErrorBudgetRemainingPercent() * 100,
            report.getSloStatus()
        );
    }
}

